import { photoByKey } from "@/lib/photo-manifest";

type Props = {
  /** Key from lib/photo-manifest.ts (generated by scripts/process-photos.mjs). */
  photoKey: string;
  /**
   * Required, not optional. The browser cannot guess how wide this image renders, and a
   * wrong `sizes` is the single most common cause of a phone downloading the desktop file.
   * Making it mandatory forces the decision at every call site.
   */
  sizes: string;
  className?: string;
  /** Hero images only. Eager-loads and raises fetch priority; everything else lazy-loads. */
  priority?: boolean;
};

/**
 * The one way images are rendered on this site.
 *
 * WHY <picture> AND NOT next/image:
 *   next/image's `formats: ['image/avif','image/webp']` only drives Next's BUILT-IN image
 *   optimizer. This site uses a pre-generated static photo pipeline, so there is no runtime
 *   optimizer to negotiate anything and that config key would be inert — config that implies
 *   behaviour which is not happening. <picture> does the negotiation in the browser itself:
 *   it walks the <source> list in order and takes the first type it supports. AVIF-capable
 *   browsers (~95%) get AVIF, everything else falls through to WebP, and there is no runtime
 *   dependency, no per-image transformation billing, and no JavaScript involved.
 *
 * NO LAYOUT SHIFT:
 *   width/height come from lib/photo-manifest.ts, which records the REAL intrinsic pixels of
 *   the files that shipped — not an assumed 1600. The browser reserves the correct box before
 *   a byte of image arrives. The AVIF and WebP files are generated at identical dimensions
 *   precisely so the reserved box is right whichever format wins.
 *
 * ALT TEXT:
 *   Comes from the manifest and cannot be overridden here. It was written from what is
 *   actually visible in each frame and verified against the source; letting call sites pass
 *   their own would let a service page quietly claim a photo shows work it does not show.
 */
export default function Photo({ photoKey, sizes, className, priority = false }: Props) {
  const p = photoByKey[photoKey];
  if (!p) {
    // Loud in dev, invisible in prod, never a broken-image icon in front of a client.
    if (process.env.NODE_ENV !== "production") {
      throw new Error(
        `<Photo photoKey="${photoKey}"> not found in lib/photo-manifest.ts. ` +
          `Run \`npm run photos\` after adding it to the MANIFEST in scripts/process-photos.mjs.`,
      );
    }
    return null;
  }

  const srcset = (small: string, full: string) =>
    `${small} ${p.smallWidth}w, ${full} ${p.width}w`;

  return (
    <picture>
      <source type="image/avif" srcSet={srcset(p.smallAvif, p.avif)} sizes={sizes} />
      <source type="image/webp" srcSet={srcset(p.smallWebp, p.webp)} sizes={sizes} />
      <img
        src={p.webp}
        width={p.width}
        height={p.height}
        alt={p.alt}
        className={className}
        loading={priority ? "eager" : "lazy"}
        decoding={priority ? "sync" : "async"}
        fetchPriority={priority ? "high" : "auto"}
      />
    </picture>
  );
}
