// GENERATED by scripts/process-photos.mjs — do not edit by hand.
// Run `npm run photos` to regenerate. Alt text lives in that script's MANIFEST.
// width/height are the REAL intrinsic dimensions of the files that ship, so markup
// can declare them and avoid layout shift. AVIF and WebP always share dimensions.

export type Photo = {
  key: string;
  avif: string;
  webp: string;
  width: number;
  height: number;
  smallAvif: string;
  smallWebp: string;
  smallWidth: number;
  smallHeight: number;
  alt: string;
};

export const photos: readonly Photo[] = [
  {
    "key": "before-01-brush-birch-grand-rapids",
    "avif": "/photos/before-01-brush-birch-grand-rapids.avif",
    "webp": "/photos/before-01-brush-birch-grand-rapids.webp",
    "width": 1100,
    "height": 825,
    "smallAvif": "/photos/before-01-brush-birch-grand-rapids-800.avif",
    "smallWebp": "/photos/before-01-brush-birch-grand-rapids-800.webp",
    "smallWidth": 800,
    "smallHeight": 600,
    "alt": "Pile of cut brush and leafy branches dumped on the grass in front of a stand of birch trees before a yard waste cleanup in Grand Rapids, Minnesota."
  },
  {
    "key": "after-01-brush-birch-grand-rapids",
    "avif": "/photos/after-01-brush-birch-grand-rapids.avif",
    "webp": "/photos/after-01-brush-birch-grand-rapids.webp",
    "width": 1200,
    "height": 900,
    "smallAvif": "/photos/after-01-brush-birch-grand-rapids-800.avif",
    "smallWebp": "/photos/after-01-brush-birch-grand-rapids-800.webp",
    "smallWidth": 800,
    "smallHeight": 600,
    "alt": "The same birch stand with the brush pile hauled away, bare ground where it sat, and the Just Junk It truck and dump trailer parked at the treeline."
  },
  {
    "key": "before-02-basement-estate-cleanout",
    "avif": "/photos/before-02-basement-estate-cleanout.avif",
    "webp": "/photos/before-02-basement-estate-cleanout.webp",
    "width": 1600,
    "height": 1200,
    "smallAvif": "/photos/before-02-basement-estate-cleanout-800.avif",
    "smallWebp": "/photos/before-02-basement-estate-cleanout-800.webp",
    "smallWidth": 800,
    "smallHeight": 600,
    "alt": "Basement full of folding chairs, tied contractor bags, cardboard boxes and a step ladder, tagged for removal during an estate cleanout in Grand Rapids, Minnesota."
  },
  {
    "key": "after-02-basement-estate-cleanout",
    "avif": "/photos/after-02-basement-estate-cleanout.avif",
    "webp": "/photos/after-02-basement-estate-cleanout.webp",
    "width": 1200,
    "height": 1600,
    "smallAvif": "/photos/after-02-basement-estate-cleanout-800.avif",
    "smallWebp": "/photos/after-02-basement-estate-cleanout-800.webp",
    "smallWidth": 600,
    "smallHeight": 800,
    "alt": "The same basement emptied to bare concrete after an estate cleanout, with only the homeowner's own paint cans left in the corner."
  },
  {
    "key": "before-03-brush-pile-wooded-lot",
    "avif": "/photos/before-03-brush-pile-wooded-lot.avif",
    "webp": "/photos/before-03-brush-pile-wooded-lot.webp",
    "width": 825,
    "height": 1100,
    "smallAvif": "/photos/before-03-brush-pile-wooded-lot-800.avif",
    "smallWebp": "/photos/before-03-brush-pile-wooded-lot-800.webp",
    "smallWidth": 600,
    "smallHeight": 800,
    "alt": "Large pile of cut brush and dead branches at the edge of a wooded lot in Itasca County, beside an overturned aluminum boat and an old truck bed."
  },
  {
    "key": "after-03-brush-pile-wooded-lot",
    "avif": "/photos/after-03-brush-pile-wooded-lot.avif",
    "webp": "/photos/after-03-brush-pile-wooded-lot.webp",
    "width": 825,
    "height": 1100,
    "smallAvif": "/photos/after-03-brush-pile-wooded-lot-800.avif",
    "smallWebp": "/photos/after-03-brush-pile-wooded-lot-800.webp",
    "smallWidth": 600,
    "smallHeight": 800,
    "alt": "The same wooded lot edge with the brush pile cleared and the ground raked clean. The boat and truck bed were not part of the job and remain in place."
  },
  {
    "key": "job-01-basement-books-estate-cleanout",
    "avif": "/photos/job-01-basement-books-estate-cleanout.avif",
    "webp": "/photos/job-01-basement-books-estate-cleanout.webp",
    "width": 1200,
    "height": 1600,
    "smallAvif": "/photos/job-01-basement-books-estate-cleanout-800.avif",
    "smallWebp": "/photos/job-01-basement-books-estate-cleanout-800.webp",
    "smallWidth": 600,
    "smallHeight": 800,
    "alt": "Basement room with a steel desk, filing cabinets and stacks of hardcover books bagged and boxed for removal during an estate cleanout in Grand Rapids, Minnesota."
  },
  {
    "key": "job-02-basement-appliances",
    "avif": "/photos/job-02-basement-appliances.avif",
    "webp": "/photos/job-02-basement-appliances.webp",
    "width": 1600,
    "height": 1200,
    "smallAvif": "/photos/job-02-basement-appliances-800.avif",
    "smallWebp": "/photos/job-02-basement-appliances-800.webp",
    "smallWidth": 800,
    "smallHeight": 600,
    "alt": "Older basement holding a washer, two dryers, a water heater and a cast iron radiator being disconnected for appliance removal in Grand Rapids, Minnesota."
  },
  {
    "key": "job-03-carport-packed-full",
    "avif": "/photos/job-03-carport-packed-full.avif",
    "webp": "/photos/job-03-carport-packed-full.webp",
    "width": 1579,
    "height": 1600,
    "smallAvif": "/photos/job-03-carport-packed-full-800.avif",
    "smallWebp": "/photos/job-03-carport-packed-full-800.webp",
    "smallWidth": 790,
    "smallHeight": 800,
    "alt": "Portable fabric carport packed wall to wall with boxes, bags, a mattress and a bicycle before a full cleanout in Itasca County, Minnesota."
  },
  {
    "key": "job-04-carport-emptied",
    "avif": "/photos/job-04-carport-emptied.avif",
    "webp": "/photos/job-04-carport-emptied.webp",
    "width": 1200,
    "height": 1600,
    "smallAvif": "/photos/job-04-carport-emptied-800.avif",
    "smallWebp": "/photos/job-04-carport-emptied-800.webp",
    "smallWidth": 600,
    "smallHeight": 800,
    "alt": "Empty portable fabric carport with a bare dirt and concrete floor after its contents were hauled away in Itasca County, Minnesota."
  },
  {
    "key": "truck-01-dump-trailer-grand-rapids",
    "avif": "/photos/truck-01-dump-trailer-grand-rapids.avif",
    "webp": "/photos/truck-01-dump-trailer-grand-rapids.webp",
    "width": 1600,
    "height": 972,
    "smallAvif": "/photos/truck-01-dump-trailer-grand-rapids-800.avif",
    "smallWebp": "/photos/truck-01-dump-trailer-grand-rapids-800.webp",
    "smallWidth": 800,
    "smallHeight": 486,
    "alt": "The Just Junk It pickup and dump trailer parked at a job site in Grand Rapids, Minnesota."
  }
];

export const photoByKey: Record<string, Photo> = Object.fromEntries(photos.map((p) => [p.key, p]));
