// GENERATED by scripts/process-photos.mjs — do not edit by hand.
// Run `npm run photos` to regenerate. Alt text lives in that script's MANIFEST.

export type Photo = {
  key: string;
  src: string;
  width: number;
  height: number;
  smallWidth: number;
  smallHeight: number;
  alt: string;
};

export const photos = [
  {
    "key": "before-01-brush-birch-grand-rapids",
    "src": "/photos/before-01-brush-birch-grand-rapids.webp",
    "width": 900,
    "height": 675,
    "smallWidth": 600,
    "smallHeight": 450,
    "alt": "Pile of cut brush and leafy branches dumped on the grass in front of a stand of birch trees before a yard waste cleanup in Grand Rapids, Minnesota."
  },
  {
    "key": "after-01-brush-birch-grand-rapids",
    "src": "/photos/after-01-brush-birch-grand-rapids.webp",
    "width": 1000,
    "height": 750,
    "smallWidth": 600,
    "smallHeight": 450,
    "alt": "The same birch stand with the brush pile hauled away, bare ground where it sat, and the Just Junk It truck and dump trailer parked at the treeline."
  },
  {
    "key": "before-02-basement-estate-cleanout",
    "src": "/photos/before-02-basement-estate-cleanout.webp",
    "width": 1600,
    "height": 1200,
    "smallWidth": 800,
    "smallHeight": 600,
    "alt": "Basement full of folding chairs, tied contractor bags, cardboard boxes and a step ladder, tagged for removal during an estate cleanout in Grand Rapids, Minnesota."
  },
  {
    "key": "after-02-basement-estate-cleanout",
    "src": "/photos/after-02-basement-estate-cleanout.webp",
    "width": 1200,
    "height": 1600,
    "smallWidth": 600,
    "smallHeight": 800,
    "alt": "The same basement emptied to bare concrete after an estate cleanout, with only the homeowner's own paint cans left in the corner."
  },
  {
    "key": "before-03-brush-pile-wooded-lot",
    "src": "/photos/before-03-brush-pile-wooded-lot.webp",
    "width": 675,
    "height": 900,
    "smallWidth": 450,
    "smallHeight": 600,
    "alt": "Large pile of cut brush and dead branches at the edge of a wooded lot in Itasca County, beside an overturned aluminum boat and an old truck bed."
  },
  {
    "key": "after-03-brush-pile-wooded-lot",
    "src": "/photos/after-03-brush-pile-wooded-lot.webp",
    "width": 675,
    "height": 900,
    "smallWidth": 525,
    "smallHeight": 700,
    "alt": "The same wooded lot edge with the brush pile cleared and the ground raked clean. The boat and truck bed were not part of the job and remain in place."
  },
  {
    "key": "job-01-basement-books-estate-cleanout",
    "src": "/photos/job-01-basement-books-estate-cleanout.webp",
    "width": 1200,
    "height": 1600,
    "smallWidth": 600,
    "smallHeight": 800,
    "alt": "Basement room with a steel desk, filing cabinets and stacks of hardcover books bagged and boxed for removal during an estate cleanout in Grand Rapids, Minnesota."
  },
  {
    "key": "job-02-basement-appliances",
    "src": "/photos/job-02-basement-appliances.webp",
    "width": 1600,
    "height": 1200,
    "smallWidth": 800,
    "smallHeight": 600,
    "alt": "Older basement holding a washer, two dryers, a water heater and a cast iron radiator being disconnected for appliance removal in Grand Rapids, Minnesota."
  },
  {
    "key": "job-03-carport-packed-full",
    "src": "/photos/job-03-carport-packed-full.webp",
    "width": 1382,
    "height": 1400,
    "smallWidth": 790,
    "smallHeight": 800,
    "alt": "Portable fabric carport packed wall to wall with boxes, bags, a mattress and a bicycle before a full cleanout in Itasca County, Minnesota."
  },
  {
    "key": "job-04-carport-emptied",
    "src": "/photos/job-04-carport-emptied.webp",
    "width": 900,
    "height": 1200,
    "smallWidth": 600,
    "smallHeight": 800,
    "alt": "Empty portable fabric carport with a bare dirt and concrete floor after its contents were hauled away in Itasca County, Minnesota."
  },
  {
    "key": "truck-01-dump-trailer-grand-rapids",
    "src": "/photos/truck-01-dump-trailer-grand-rapids.webp",
    "width": 1200,
    "height": 729,
    "smallWidth": 800,
    "smallHeight": 486,
    "alt": "The Just Junk It pickup and dump trailer parked at a job site in Grand Rapids, Minnesota."
  }
] as const satisfies readonly Photo[];

export const photoByKey = Object.fromEntries(photos.map((p) => [p.key, p])) as Record<string, Photo>;
